version: "3.9"

volumes:
    db-store:

services:
  web:
    image: nginx:1.21.6-alpine
    container_name: web
    volumes:
      - ./src/docker/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
      - app

  app:
    build: ./src/docker/app
    container_name: app
    volumes:
      - ./src/:/var/www
    depends_on:
      - db

  db:
    build: ./src/docker/db
    container_name: db
    volumes:
      - ./src/docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
