name: Laravel-Test

on: [push]

jobs:
  laravel-tests:
    name: laravel phpunit test
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_testing

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Cache Composer Package
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-composer
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ env.cache-name }}-
            ${{ runner.os }}-composer-
      - name: Install Composer Package
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          composer install --no-ansi --no-interaction --no-progress --prefer-dist
      - name: Setup Laravel Exection
        run: |
          chmod -R 777 storage bootstrap/cache
          php artisan cache:clear
          php artisan config:clear
      - name: Execute PHPUnit
        env:
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          vendor/bin/phpunit
