name: 'Add issue link'
on:
  pull_request:
    types: [opened]

jobs:
  add-issue-link:
    runs-on: ubuntu-20.04
    steps:
      - uses: tkt-actions/add-issue-links@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-prefix: "feat_#"
          resolve: "true"
